// Array of search queries
const SEARCH_QUERIES = [
  'football',
  'music',
  'news',
  'technology',
  'cooking',
  'travel',
  'fitness',
  'gaming',
  'movies',
  'comedy',
  'education',
  'fashion',
  'business',
  'science',
  'health',
  'art',
  'pets',
  'DIY',
  'history',
  'politics',
  'entertainment',
  'cars',
  'nature',
  'space',
  'programming',
  'photography',
  'recipes',
  'podcasts',
  'virtual reality',
  'home decor',
  'product reviews',
  'book reviews',
  'cricket',
  'gardening',
  'architecture',
  'documentaries',
  'pop culture',
  'celebrity interviews',
  'motivational speeches',
  'dance tutorials',
  'instrumental music',
  'self-improvement',
  'financial advice',
  'language learning',
  'travel vlogs',
  'unboxing videos',
  'anime reviews',
  'meditation',
  'graphic design',
  'magic tricks',
  'technology reviews',
  'game development',
  'parenting tips',
  'food challenges',
  'mindfulness',
  'urban exploration',
  'mukbang',
  'book summaries',
  'fitness challenges',
  'science experiments',
  'budget travel tips',
  'daily vlogs',
  'comic book reviews',
  'interviews',
  'painting tutorials',
  'mind-bending puzzles',
  'virtual tours',
  'reaction videos',
  'celebrity gossip',
  'cooking competitions',
  'animated shorts',
  'life hacks',
  'role-playing games',
  'toy reviews',
  'how-to guides',
  'futuristic technology',
  'personal finance',
  'home workouts',
  'educational cartoons',
  'travel hacks',
  'video essays',
  'social experiments',
  'language challenges',
  'pet care tips',
  'coding tutorials',
  'medieval history',
  'cryptocurrency news',
  'book recommendations',
  'tech gadgets',
  'space exploration',
  'haunted places',
  'classic movie reviews',
  'riddles and brain teasers',
  'DIY fashion',
  'minimalist living',
  'ancient civilizations',
  'plant-based recipes',
  'calligraphy tutorials',
  'foreign language films',
  'paranormal investigations',
  'experimental music',
  'robotics',
  'sustainable living',
  'yoga workouts',
  'film festivals',
  'virtual concerts',
  'nature documentaries',
  'educational rap',
  'escape room challenges',
  'collectibles reviews'
];

export default SEARCH_QUERIES